### ISSUE TITLE
[Question] Prefer Sling Model constructor injection?

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#1018]
Is there a reason that this project eschews using constructor injection for sling models?

I personally find that constructor injection is a lot easier for Java developers to understand because there's less "magic". 

Sure, any time there are annotations involved there is _some_ magic, but with constructor injection the entire lifecycle of the object is well understood because it is identical to standard java objects.

Constructor injection also allows for fields to be marked as final when they are final, which i find leads to better quality code and fewer bugs; in java, marking final fields as final is generally accepted to be best practice.

It also allows a model to *not* keep a reference to an injected variable that is only ever used in its initializer/constructor. Better, in my opinion, to not hang on to useless references that are only needed during the initialization of a model.

**Comment by joerghoh** [comment]
<personal opinion>
Constructor injection for models hasn't been there from the beginning; and because most AEM devleopers are familiar with the OSGI @Reference statements, it's not a problem for them at all. I agree that for someone with less experience with AEM constructor injection is probably more convenient. 

That means it's a question of personal style, and if you prefer towrite your Sling Models using Constructor injection I am fine with that. And I am quite sure that the majority of the other people contributing here are too.

</personal opinion>
