### ISSUE TITLE
[Page] Support for brand slug in page title

### ISSUE THREAD

**Issue by js-headwire** [adobe/aem-core-wcm-components#1050]
## Support for Brand Slug in Page Title

**Is your feature request related to a problem? Please describe.**
The title element in a lot of sites often has a common slug appended at the end.  Some examples:
```
<title>VW Model Lineup – Cars and SUVs | Volkswagen</title>
<title>News &amp; Insights  | CVS Health</title>
<title>Model 3 | Tesla</title>
```
Adding these to the end of each `jcr:title` via page properties requires work to be done on every page in the content hierarchy.

**Describe the solution you'd like**
A way to dynamically append a slug to titles that doesn't require a lot of maintenance work from authors:
1. Adding a Brand Slug to Page Properties, and then having pages inherit that in their head.html
2. Adding an Override checkbox allowing authors to specify a new slug (or none at all) at and below a level in the hierarchy.

**Are there alternatives?**
Changing `PageImpl.title` computation to flow from an osgi service, consulting N factory configs' for matching paths in order to use one of their brand slugs.  I like this less than the Page Properties approach because it puts the task on an administrator/developer when an author should control the title.

**Documentation**
Use Brand Slug in Page Properties to maintain a value that gets added to the end of the <title> element on this page and every page below it.  Checking the "override" box allows the user to specify a new value (or no value at all) that overrides any value inherited from a page above.
![brandslug](https://user-images.githubusercontent.com/66262327/84290218-05e26580-ab09-11ea-9512-871e0165cae1.png)

**Comment by gabrielwalt** [comment]
The name "Brand Slug" is very technical. I'm ok to keep it in a description text, to detail what is being meant, but the main term "Title Appendix" seems more understandable.

We started to use context-aware configs for many things indeed, but as we don't have a UI for authors to edit the values yet, for the time being, I'd limit using them only for configs that are controlled by the developer persona (eg. site-specific feature flags, like Data Layer, or API keys, like for the PDF viewer).

I'd, therefore, keep that option in the page dialog. Also, branding must be consistent indeed, but I'd estimate that there are more cases where authors would have legitimate issues if they cannot easily control that appendix (eg. in the special cases described by Kyle), than cases where authors would cause trouble because they can control that appendix (not only because of the lack of context-aware UI but also because of the complexity and maybe even lacking ACL to create a context-aware config for the sub-sections).

Regarding the UX, I'd solve it as follows:
<img width="532" alt="appendix" src="https://user-images.githubusercontent.com/130083/84489255-b2efe600-aca1-11ea-82c8-1d3dd9fce166.png">
The info button could say something like the following text: "A brand slug that is appended to the title of all child pages."

**Comment by reusr1** [comment]
@gabrielwalt thanks for your comments. I am wondering if there are any plans for open graph meta tags. For example this 'title appendix' as you named it above would potentially correspond to the og:site_name meta tag. 

more info at: https://ogp.me/#optional

**Comment by gabrielwalt** [comment]
Sure, all meaningful meta tags that improve SEO make sense to be added. I agree that it would make sense to add a `og:site_name` tag when the title appendix is set would make sense.

**Comment by bpauli** [comment]
fixed in https://github.com/adobe/aem-core-wcm-components/commit/b744346dcdcf17b07f76ebc9b18b90ec367cb7a7
