### ISSUE TITLE
[Container] No allowed components displayed for locked container if layout in policy is responsive grid

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-core-wcm-components#1148]
Since #1094 it's possible to set the container layout in content policy. If this feature is used and the container layout is set to "responsive grid", no allowed components are displayed in template editor.

Example of locked container component in template editor with layout in policy set to "Responsive Grid":
![policy-responsive-grid](https://user-images.githubusercontent.com/5614031/91074074-595e4d00-e63c-11ea-989f-466c8f987d07.png)

Example of locked container component in template editor with layout in policy set to "Simple" (or default):
![policy-simple](https://user-images.githubusercontent.com/5614031/91074086-5d8a6a80-e63c-11ea-9e77-7130dadee4fa.png)

**Comment by jckautzmann** [comment]
@stefanseifert Could you please detail the exact steps in order to reproduce this issue? Thx!

**Comment by vladbailescu** [comment]
Steps to reproduce:

* Add a Core Components container to a template
* Make the container responsive (using default in content policy)
* Add some components as allowed inside the container
*Unlock the container

Expected result:

* Allowed components would be listed in the container so that they can be reviewed and content policies can be set for them

Actual result:

* The container is empty

**Comment by vladbailescu** [comment]
I was able to reproduce the issue with the above steps. I think it's worth fixing it on a product level, so that the allowed components show regardless of any extra wrappers that a container might add. @stefanseifert , if you have a specific use-case for a customer affected by this, please file a request with customer support and reference the internal Adobe issue CQ-4305421!
