### ISSUE TITLE
Publish javadoc

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1191]
## Feature Request

**Is your feature request related to a problem? Please describe.**
It would be nice to not only push the javadoc as JAR to Maven Central but also publish it somewhere on the web. 
This would be especially useful if you expand the API in the future to not contain of the model interfaces.

**Describe the solution you'd like**
A link on the readme pointing to the javadoc for the most recent version

**Proposed solutions**
* Either a link to https://www.javadoc.io/doc/com.adobe.cq/core.wcm.components.core or
* Publish website to GH pages or
* Publish to some other web server

**Comment by msagolj** [comment]
Hi @kwin, your first proposal looks like a good and easy solution. But before adding that link I think we need to take a look at the generated javadoc since the layout is broken if you look at the page:

https://www.javadoc.io/doc/com.adobe.cq/core.wcm.components.core

its unrelated to the hosting, it looks like css is missing, not sure why. If I check the different versions on www.javadoc.io this has been broken since forever :)

**Comment by kwin** [comment]
This is a problem with your javadoc jar provided at https://repo1.maven.org/maven2/com/adobe/cq/core.wcm.components.core/2.11.1/. The contained `stylesheet.css` is almost empty. Probably something wrongly configured in `maven-javadoc-plugin`

**Comment by kwin** [comment]
Probably this is due to https://github.com/adobe/aem-core-wcm-components/blob/f8784d226e6b2fec53aafb5df712465519535688/parent/pom.xml#L80

**Comment by msagolj** [comment]
PR merged. closing Issue
