### ISSUE TITLE
Understanding the purpose of the 'Link items' feature

### ISSUE THREAD

**Issue by evieperren** [adobe/aem-core-wcm-components#1201]
Hello, 

Not a bug or a feature - but maybe a suggestion to add more to the current documentation. https://docs.adobe.com/content/help/en/experience-manager-core-components/using/components/list.html

I have made use of the out-the-box list component to render links to pages within our website. The functionality works well but I am not sure on what the 'Link items' checkbox really enables. From the code, it seems to conditionally render a div, which has styling attached. However, the tooltip 'Link items to the corresponding page' does not match the functionality I have found. 

Is there something I am missing? Or should the documentation provide more detail

![image](https://user-images.githubusercontent.com/48217310/95108739-92a5d480-0733-11eb-9c0f-96e5c8a08829.png)

![image](https://user-images.githubusercontent.com/48217310/95108656-743fd900-0733-11eb-8544-3509892524a1.png)

**Comment by dhardtke** [comment]
I don't know where the code snippet from your second screenshot is from because I can't find `cmp-list__item-wrapper` anywhere in the current code base of this repo, but after I had a quick look at the list component's current templates I think I can answer your question:

https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/list/v2/list/item.html#L18
Here you can see the `a` element is only rendered if the `linkItems` checkbox is not checked.

This is also true for v1 of the _list_ component: https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/list/v1/list/item.html#L18

**Comment by vladbailescu** [comment]
@evieperren , `linkItems` is used to control if each item should link to it's corresponding page. See https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/list/v2/list#edit-dialog-properties

> `./linkItems` - if set to `true` the list will link all items to the corresponding pages

**Comment by evieperren** [comment]
Thank you @dhardtke and @vladbailescu. Closing this now as it is clear to me :)
