### ISSUE TITLE
Html Page Items context-aware configuration not editable

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-core-wcm-components#1234]
PR #1203 introduced support for including custom CSS, JS and metadata tags using a "html page item" concepts based on context-aware configuration.

however the annotation class `com.adobe.cq.wcm.core.components.config.HtmlPageItemsConfig` does not reflect what's editable - it contains only definition for the prefix path, but not for the items and properties that can be defined inside of it. with caconfig it's possible to describe these nested configurations as well, and only when this metadata is present it can be edited with configuration editors like https://wcm.io/caconfig/editor/

here is an example for describing a nested configuration in caconfig annotation classes:
https://github.com/wcm-io/wcm-io-caconfig/blob/develop/sample-app/bundles/core/src/main/java/io/wcm/caconfig/sample/config/ConfigSampleNested.java

please also not that the code in PageImpl is using the "low-level" ConfigrationResourceResolver which should not be done in this case as it should only be used for configuration not described via annotations and not stored in "sling:configs". when the configuration is fully described via it's annotation class the ConfigurationResolver can be used and all item data can be accessed in a type-safe way.

it would also be nice to have this feature documented and and example included in the component library. currently i do not fully get how this "path prefix" feature is supposed to work.

**Comment by vladbailescu** [comment]
@stefanseifert , the `HtmlPageItemsConfig` is documented at https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/page/v2/page#loading-of-context-aware-cssjs . The `prefixPath` is prepended to the items `src` or `href`, in case you deploy your CSS/JS in different folders per build, for example `//my.location/assets/build0x`:

```
//my.location/assets/build01
    /css/main.css
    /js/main.js
...
//my.location/assets/build05
    /css/main.css
    /js/main.js
```

I was unaware we could use this type of nesting instead of of the ConfigurationResourceResolver, that's something we could definitely improve. I think it would be nice if the whole config tree would be exposed as an API.

**Comment by bpauli** [comment]
fixed in https://github.com/adobe/aem-core-wcm-components/commit/8831a0a2a7e39a64d5e44d60f2efd9888bcdeb15
