### ISSUE TITLE
[Page] Bulk Edit Page Properties doesn't work

### ISSUE THREAD

**Issue by knennigtri** [adobe/aem-core-wcm-components#1299]
## Bug Report

**Current Behavior**
In AEM Sites, I should be able to select multiple pages and do a bulk property update. The UI shows up but no page properties. My pages are using a proxy component to the  Core Page component. I have tested this on WKND and a near blank project from the archetype. Same result.
![image](https://user-images.githubusercontent.com/2186704/100934443-b92a8680-34bc-11eb-9005-be6c00e42a8c.png)
![image](https://user-images.githubusercontent.com/2186704/100934361-a3b55c80-34bc-11eb-8e3b-1692b9bc0546.png)

**Expected behavior/code**
When i select multiple pages and go into the page properties, I should get the bulk properties editor and modify different page properties for multiple pages.
![image](https://user-images.githubusercontent.com/2186704/100935037-9482de80-34bd-11eb-8807-c68ec408fd75.png)

**Environment**
Running on CS or a local SDK
- AEM Build 2020.11.4506.20201112T235200Z-201028
- Core Components installed by default = 2.11.1

**Comment by msagolj** [comment]
@knennigtri This is an issue with the site admin and has nothing to do with core components , so it should be reported to Adobe support. But i took a quick look at the documentation and I guess it works as expected:

https://experienceleague.adobe.com/docs/experience-manager-65/developing/extending-aem/bulk-editing.html?lang=en#configuring-your-page-for-bulk-editing-of-page-properties

`Due to the possibility of different values, page properties are not enabled for bulk editing as default. They must be explicitly allowed (enabled).`

so please check first if that is the case. If you still have this issue than please report this to the Adobe Support.
