### ISSUE TITLE
[Navigation] Exclude root levels options

### ISSUE THREAD

**Issue by joostvdbroek93** [adobe/aem-core-wcm-components#151]
**Requested feature**

It would be nice to have a level option in the Navigation component's dialog/design dialog that uses [page.getAbsoluteParent(int)](https://helpx.adobe.com/experience-manager/6-3/sites/developing/using/reference-materials/javadoc/com/day/cq/wcm/api/Page.html#getAbsoluteParent(int)) for rendering the navigation items.

**Example**

An author specifies level 3 in the navigation component's dialog and we have the following pages:

/content/my-site/en/foo/foo1
/content/my-site/en/foo/foo2
/content/my-site/en/anotherfoo/anotherfoo1
/content/my-site/en/anotherfoo/anotherfoo2

In this case, foo and anotherfoo are level 3 pages.

On the /content/my-site/en page, the navigation should render nothing.

On the /content/my-site/en/foo page, the navigation component should render:
foo1
foo2

On the /content/my-site/en/anotherfoo page, the navigation component should render:
anotherfoo1
anotherfoo2

On the /content/my-site/en/anotherfoo/anotherfoo1 page (or deeper), the navigation component should still render:
anotherfoo1
anotherfoo2

Thanks in advance

**Comment by gabrielwalt** [comment]
Agreed, it would make sense to extend the option "exclude navigation root" to something a bit more generic, like the number of start levels to exclude.

Instead of using the absolute parent level which isn't necessarily meaningful for authors, I'd rather use a relative number, like:
* 0 = show the root level
* 1 = exclude the root level
* 2 = exclude the 1 more level than the root
* etc.

So in Joost's example we'd configure the navigation component as follows:
* Navigation root = "/content/my-site/en"
* Exclude root levels = 2

**Comment by Shivanshmathur** [comment]
@gabrielwalt I'm guessing this has to be implemented in Navigation v2 right?

**Comment by andreeadracea** [comment]
The enhancement was implemented.

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
