### ISSUE TITLE
[Core] [Unit Test] Core module unit tests take very long time due to heavy GC activity

### ISSUE THREAD

**Issue by puradawid** [adobe/aem-core-wcm-components#1544]
## Bug Report

**Current Behavior**
Once running a full set of tests within the core module, each test is gradually taking more time to execute, to some very long times like minutes. For low memory limit (i.e. 1G) it stops executing. Running them separately, or in a small set, does not bring this effect. The problem seems to be caused by some either memory leak or heavy memory work - connected monitor, such as VisualVM, shows the significant activity of GC  (more than 10% of processor's time) related to the moment when the test suite slows down.

**Expected behavior/code**
These tests are not complicated and should run smoothly, taking normally around 100ms per test and they should not require that long time to execute.

**Environment**
- current master branch, running it on a local machine, special EC2 instance free of other dependencies, and it also has the same effect (although I couldn't connect VisuamVM there) in GitHub actions (based on logs). 

**Possible Solution**
Tracking down the memory leak and fixing this problem either by removing the library that causes it or fixing the code.

**Additional context / Screenshots**
I will add screenshots of VisualVM if necessary, but I think this may be reproduced everywhere, without any significant difference between forkCount values in Maven or MAVEN_OPTS settings. It is more visible when forkCount=0, given that JVM is already running for some time, but it impacts the most when forkCount = 1, and the process has no that much memory to allocate that potential memory leak.

**Comment by piwanowicz** [comment]
I found  memory and performance issue in SLF4J Test logging library used in tests. This library is simple SLF4J implementation that stores logs in memory and the issue is that it stores all log messages, from level TRACE to ERROR. During tests any class from classpath will add logs to memory. One test class, which use AemContext, can generate tens of thousands logs. Running all test classes leads in a short time to collection with hundreds of thousands log messages. But it's not the biggest problem. We can increase memory but still performance issue exists. SLF4J Test library uses not the best type of collection for storing logs - CopyOnWriteArrayList. It means that for every log message a new array list will be created. When tests get to the point when there are hundreds of thousands log messages, then adding a single message is very expensive operation.  And of course GC has also a lot of work to do.

I see two solutions to resolve this problem:
1. Change logging library used in tests.
2. Rewrite tests - do not rely on log messages in tests.

**Comment by vladbailescu** [comment]
@piwanowicz , thanks for the analysis. You're right, this was due to use of http://projects.lidalia.org.uk/slf4j-test library. As a workaround I added a cleanup extension to all our tests (#1552), that reduced total test run time to 1-2 minutes.

**Comment by vladbailescu** [comment]
@kwin , thanks for the suggestion but our use cases were simple enough to replace them with simple Mockito `verify`
