### ISSUE TITLE
Export model implementations to make extending components easier

### ISSUE THREAD

**Issue by nachocual** [adobe/aem-core-wcm-components#166]
Currently the model implementation classes are in an internal package, and thus not exported by the bundle.

I get the idea behind this, but when extending a core component in a way that requires creating a new model it'd be useful to be able to inherit from  the existing implementation without having to copy the code over. You'd be able to do something similar to what the v2 models do on your own project.

**Comment by vladbailescu** [comment]
Reusing the out-of-the-box implementations is possible by using [Delegation Pattern for Sling Models](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/wiki/Delegation-Pattern-for-Sling-Models).

**Comment by nachocual** [comment]
Oh, I missed that one, thanks for the link!

**Comment by felipeabellan** [comment]
So we are pretty much stuck to whatever was decided to be public on the class? What if the changes I need to make are in a private method? such as instead of using the properties, I want to use an inheritance valuemap? It should be a fairly minor change, but forcing me to overwrite the whole class for this

**Comment by jckautzmann** [comment]
@felipeabellan A private method is part of the implementation and cannot be accessed/modified externally. In case you need to access a property that is not exposed by the API, you'll need to provide your own implementation.

**Comment by felipeabellan** [comment]
Ok yeah, I understand that. I was hoping that wouldn't be the case as for example Navigation is a fairly big class and is very good at what it does, but can't seem to modify it to use inherited properties without having to override the complete class. Bummer.

**Comment by jckautzmann** [comment]
I agree that sligthly modifying the implementation requires some customization effort.

**Comment by paul-bjorkstrand** [comment]
Since this is meant to be a "jump start" package, reducing the amount of development needed for standard functionality, it does a great job of augmenting the OOTB AEM component library. It falls flat on its face, when you just want to extend the functionality, adding your own flavor to the components. The most egregious of these are the Page models (v1, v2). While they are a great start for any page component that needs to be built in a project, it doesn't go far enough to allow for customizations.

By not allowing the implementation classes to be extended, you are effectively saying "do it our way, because we have thought of everything." In my experience, every library that does this makes itself frustrating to use, until it is eventually refactored out of the project. That refactoring often comes with a metric ton of copied code, and additional maintenance burden, which can be avoided.

While the delegation pattern in sling models helps with some of this, it is still frustrating to add the delegating boilerplate to a model.

Besides this, allowing the your classes to be extended (where appropriate) perfectly fits the SOLID open/closed principle: the classes will be open to extension, but still closed for modification.

**Comment by bpauli** [comment]
@paul-bjorkstrand, I think there are some valid points in your comment. I'll reopen this issue to continue the discussion. Maybe we can develop an idea how to customise easier the OOTB implementation beside the delegation pattern.

**Comment by paul-bjorkstrand** [comment]
This is also being discussed in #503. This Should this one be closed in favor of that one? This seems to be just one suggestion, but #503 seems to be a bigger conversation around extensibility.

**Comment by gabrielwalt** [comment]
I'm closing this issue now in favor of continuing the discussion, ideally on the mailing list now that we have it: https://groups.google.com/forum/#!forum/aem-core-components-dev
