### ISSUE TITLE
Cannot get datalayer to enable

### ISSUE THREAD

**Issue by pawee-del** [adobe/aem-core-wcm-components#1731]
### Expected Behaviour
window.adobeDataLayer.getState();
 to show something
### Actual Behaviour
window.adobeDataLayer.getState();
throwing null on console
#### Steps to Reproduce
current project created with older archetype, not  AEM Project Archetype v. 24+ , will that be the cause of the issue?
#### Platform and Version
AEM Cloud SDK

**Comment by richardhand** [comment]
@pawee-del - yes, support for the data layer was added in the archetype in v.24+ so that is likely to be the problem if you used a previous version. For documentation on installation and activation of the data layer, please see this document: https://experienceleague.adobe.com/docs/experience-manager-core-components/using/developing/data-layer/overview.html?lang=en#installation-activation 

Closing this issue, if you are still having problems getting set up with the data layer, just reopen it and provide more details on the steps you took.
