### ISSUE TITLE
Categories object not populated when using com.adobe.cq.wcm.core.components.models.ClientLibraries.

### ISSUE THREAD

**Issue by gmartinelo** [adobe/aem-core-wcm-components#1808]
## Bug Report

**Current Behavior**

The 'categories' property never gets populated with the desired values in the model and it seems to be instanciated with an object of type com.day.cq.i18n.

I'm following this documentation:
https://experienceleague.adobe.com/docs/experience-manager-core-components/using/developing/including-clientlibs.html?lang=en

`<sly data-sly-use.clientlibs="${'com.adobe.cq.wcm.core.components.models.ClientLibraries' @
    categories='otf.vanilla.homepage', async=true}">
    ${clientlibs.jsIncludes @ context="unsafe"}
</sly>
`

The resourceTypes property seems to have the same behavior described previously. Async, defer, crossorigin,media and onload are populated correctly.

**Expected behavior/code**
Categories object should have the values passed from HTL.

**Environment**
- AEM version and patch level: 6.5.8
- Core Components version: 2.17.8
- JRE version: Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)

**Additional context / Screenshots**
Page.html
![image](https://user-images.githubusercontent.com/6833548/131531698-d7c7c1b1-bf28-42d9-a428-9ad2fce7a891.png)

ClientLibrariesImpl.java
![image](https://user-images.githubusercontent.com/6833548/131532070-a9861a82-cf36-41c2-8a18-f0ec1d78ee92.png)

![image](https://user-images.githubusercontent.com/6833548/131532177-1899898b-a329-4c2e-a2aa-677616867aa2.png)

![image](https://user-images.githubusercontent.com/6833548/131532286-36a840b9-da6a-4604-ba83-bfb3511a7f74.png)

**Comment by Jdruwe** [comment]
I am seeing the exact same behaviour, this is not working indeed.

**Comment by ky940819** [comment]
I see the same issue when the named property is ***not*** set in `data-sly-call` attributes. 

For example, the code posted above works properly for me (insofar as it properly sets the `categories` field in the model); however the `resourceTypes` field just has some other object injected. In my case that is the `ReferrerFilter.ConfigurationPrinter`. 

If I change the htl to set the `resourceTypes` attribute but not the `categories` attribute, then the `categories` field in the model has a seemingly random object injected.

My suspicion is that since both the `categories` and `resourceTypes` field types are `Object`, it might just be sticking in something /  anything / whatever is at the top of some list. Since the field type is `Object` it can stick anything in there. 

This might be an issue for Sling, to make sure that an object isn't injected unless the name matches - even if the object type is compatible with something else. 

This is all just speculation, I didn't step through the entire field injection resolution. 

That said, changing the `@Inject` annotation in `ClientLibrariesImpl` resolves the random object injection in my tests.
Example:
```Java
public class ClientLibrariesImpl implements ClientLibraries {

    // ....

    @RequestAttribute(injectionStrategy = InjectionStrategy.OPTIONAL, name = OPTION_RESOURCE_TYPES)
    Object resourceTypes;

    // ....

    @RequestAttribute(injectionStrategy = InjectionStrategy.OPTIONAL, name = OPTION_CATEGORIES)
    private Object categories;

    // ....
}
```

@gmartinelo, do those changes resolve your issue?

**Comment by gunakar89** [comment]
This is still not working

**Comment by shajiahmed** [comment]
I still see this issue. My environment is as follows
Archetype:41
AEM 6.5.15
AEM core components 2.22.0
