### ISSUE TITLE
[Style System] AppliedCssClassNames are not exported in LayoutContainer Sling Model

### ISSUE THREAD

**Issue by friendlymahi** [adobe/aem-core-wcm-components#1889]
Please refer to https://github.com/adobe/aem-react-editable-components/issues/83 for complete details.

Original Reporter - @cthio

**Comment by gabrielwalt** [comment]
Thanks @friendlymahi,

We've just fixed this issue for Cloud Service and the change will probably be released in the January update. 

But as it seems, you also need that change for 6.5. Could you open a support ticket for that, so that we can get some priority to back-port this change also to 6.5? The internal reference number is SITES-3647.

Thanks!

**Comment by friendlymahi** [comment]
@gabrielwalt - Happy new year and hope you are doing well. Any update on this request? Any time line on the January release that covers this fix?

Thanks

**Comment by kapil-gahlawat** [comment]
@gabrielwalt This issue was marked as fixed in 6.5.12.0, which was released last month. It is working in this particular case. However, there is a corner case where it is not working. Here are the steps to reproduce:

1. We are using 6.5.12.0 and SPA react.
2. Create an Experience fragment template and LOCK the container in the template structure. Apply style to the container in the template structure. I added a couple of components inside this container. Make sure to LOCK the container and apply the style.
3. Now, create an experience fragment from the template created above. Experience fragments will have the style that we applied in the structure. So, it is working as expected.
4. Now create a normal page using spa-page-template or any template that you like and drag and drop Experience fragment component inside the page. Now, configure the path to the experience fragment that we created in the step 2. Now experience fragment inside your page will not look the same as the style that we applied in the step 1 are not being applied in the page.

Summary: Applied style is working fine inside the experience fragment but when you consume this same experience fragment in a page using the Experience Fragment Component, style is not being applied.

Note: If you drag and drop the container inside Experience fragment and apply style and then use this experience fragment on a page, this style is working absolutely fine. The only specific case it is not working is: Container is in the structure of experience fragment template and Locked.
