### ISSUE TITLE
Support for image/webp

### ISSUE THREAD

**Issue by danielkoch** [adobe/aem-core-wcm-components#2028]
## Feature Request

Provide solution for using webp images within the image component (including creating of responsive images/renditions).

The only problem that I can see for now is the missing IE11 support (could now find any information which browser do you support, no browserlist or anything else. Looking at the javascript looks like you're aim to still have support for IE11?)

I already saw this issue: https://github.com/adobe/aem-core-wcm-components/issues/710  – but looks like this was more an accident.

**Questions**
Do you plan to introduce webp support to the AEM core components?
Are there plans regarding timeline?

**Documentation**
General description: https://developers.google.com/speed/webp/
Browser support: https://caniuse.com/webp

**Comment by gabrielwalt** [comment]
Hi Daniel,

We do plan on adding WebP support to the Core Components, and the timeline should be around beginning of H2 2022 (and as always with roadmaps, things can change). This will be done with a new image delivery service that will not use the adaptive image servlet anymore. As this will be a cloud-specific feature, it means that it will only be available for Cloud Service for the time being.

The implementation in the Core Component will likely use something like a `picture` element, so that the browsers can fallback to other formats if necessary.

Closing this issue for now as we won't use it to track the WebP implementation.

**Comment by morerajuan** [comment]
it would be good to know if the feature was added, and in which service pach was allocated!

**Comment by yaswanthvanukuri-work** [comment]
@gabrielwalt @danielkoch 
Hi Team,

I wanted to follow up on support for handling WebP images in the Image Core component. We are currently on AEM version 6.5.17 (Adobe Managed service) with the Core component at version 2.22.0. Please let me know if this is something being considered for a future release.
Upon further research, I've found documentation indicating support for WebP images in AEM as a Cloud Service (AEMaaCS), but not for on-premises AEM installations or AEM Managed Services (AMS).
I'm interested in understanding if this capability could become available for us in the future through an customizations.

Thanks,
Yaswanth
