### ISSUE TITLE
[Accessibility][Language Navigation] Chevron icon

### ISSUE THREAD

**Issue by Gajalakshmi0408** [adobe/aem-core-wcm-components#2067]
**Component : core/wcm/components/languagenavigation/v1/languagenavigation**
@gabrielwalt  The component should have a visual indicator that it is a dropdown.
The keyboard-only user would never know there is a dropdown here and SR users would not know how to use it.
**Chevron** or **Dropdown** icon should be present beside the controls to indicate the sub-menu items when elements of content are collapsed.
Attached below is an example with chevron icon. It is not available with core component.
<img width="459" alt="chevron" src="https://user-images.githubusercontent.com/76493052/162172281-a9bde48b-a7ec-4049-b4d6-52494663fb95.PNG">
This icon is used to signify that there is content that can be toggled open and closed.

**Comment by gabrielwalt** [comment]
The language navigation component isn't offering any drop-down behavior as it is provided out of the box. Looking at the [Component Library](https://www.aemcomponents.dev/content/core-components-examples/library/core-structure/language-navigation/language-structure/us/en/language-navigation.html), you can see that all the Core Components provide is the listing of the links to switch the language.

How these links then get displayed as a drop-down (or differently) is a theming effort that is left to the project. The reason is that sites have very different ways to display the navigation items, and the Core Components don't want to bloat implementations with CSS and JS that might not be used by the sites.

To theme the language navigation as a drop-down, the [Standard Site Template](https://github.com/adobe/aem-site-template-standard/) illustrates an example. That example even has a chevron as you require for accessibility.

Below you have the CSS and JS code applied to the language navigation to make that happen (which would require project-specific adjustments as described above):
* https://github.com/adobe/aem-site-template-standard/blob/bd759ee6374c17e36a57084c244568e3fd86d20c/theme/src/components/experiencefragment/_experiencefragment_header.scss#L113-L351
* https://github.com/adobe/aem-site-template-standard/blob/bd759ee6374c17e36a57084c244568e3fd86d20c/theme/src/components/experiencefragment/change_flag.js

Therefore closing this issue.
