### ISSUE TITLE
[Title] Add ID to support anchors

### ISSUE THREAD

**Issue by vladbailescu** [adobe/aem-core-wcm-components#212]
It would be useful if titles would support anchors so you can link to a specific section of the page.

**Comment by gabrielwalt** [comment]
(CQ-4246477)

**Comment by gabrielwalt** [comment]
**Acceptance Criteria**

- The IDs must be guaranteed to be unique, otherwise the page might be invalid HTML. To guarantee it to be unique, the hash of the component's path can be used.
- Optionally, the author should be able to set an anchor name to be used for the ID instead of the automatically generated hash.

**Comment by gabrielwalt** [comment]
An additional consideration that I got by diving into general requirements for analytics, is that we should actually add IDs to all components, this would make it easier to add tracking to them if desired. If this is the case, should we maybe move this logic to the product and make it part of the Style System?

**Comment by richardhand** [comment]
This issue will be fixed by #535, closing here as duplicate.
