### ISSUE TITLE
Veracode Findings - CWE 99 Improper Control of Resource Identifiers ('Resource Injection')

### ISSUE THREAD

**Issue by Saminshri** [adobe/aem-core-wcm-components#2170]
Thank you for contacting us. We have opened an investigation, and will get back to you if we have any questions or trouble reproducing this issue. In the meantime, we will remove these posts while we investigate internally.

Please reference case SITES-6378 in any future correspondence related to this issue, and feel free to reach out to [PSIRT@adobe.com](mailto:PSIRT@adobe.com) for periodic status updates.

Thank you,

AEM Security

**Comment by jckautzmann** [comment]
@adobe export issue to Jira project SITES as Story

**Comment by acollign** [comment]
> ✅ Jira issue SITES-6378 is successfully created for this GitHub issue.

Closing. Please reference case SITES-6378 in any future correspondence related to this issue, and feel free to reach out to [PSIRT@adobe.com](mailto:PSIRT@adobe.com) for periodic status updates.

I wanted to let you know that Adobe has a HackerOne program that accepts web vulnerabilities that fall into Adobe's HackerOne policy and scope defined here:  https://hackerone.com/adobe. Reporting Adobe bugs via our Adobe HackerOne portal is our standard triage process, and will ensure this issue is reviewed/remediated as efficiently as possible.
