### ISSUE TITLE
Image urls should contain the original filename

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#274]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently the image url contains the path to the image component on the page (compare with https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/wiki/The-Adaptive-Image-Servlet#url-formats) but does not contain the actual filename of the referenced asset or an artificial filename set through the editor.

**Describe the solution you'd like**
For SEO purposes a meaningful filename should be contained in the URL. Preferably between the timestamp and the extension. That filename should be derived from the DAM assets node name (or  maybe some metadata property which contains the original filename) or from a locally overwritten property (maintained in the image dialog). Also the filename should be send with an according `Content-Disposition` header (https://tools.ietf.org/html/rfc6266#section-4.3) with a filename set to that value.

Proposed URL format should look like
```<image-component-path>.<selectors>.<extension>/<timestamp>/<filename>.<extension>```

**Comment by ompandeyinfy** [comment]
This certainly needs an enhancement on `AdaptiveImageServlet` because it validates `requestLastModifiedSuffix  `  [1], if it's not a valid timestamp and not  `lastModifiedEpoch`, sets a response with `302`

[1] https://github.com/adobe/aem-core-wcm-components/blob/6ef2ae39a4e2f42a4fa7466ad101643e4979fb7a/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java#L189]

**Comment by richardhand** [comment]
This was added with the merge of #419 and is on master. It will be available in the upcoming [2.3.0](https://github.com/adobe/aem-core-wcm-components/milestone/10)
 release.
