### ISSUE TITLE
[List] Creating a list with tagging requires read rights on tags for everyone

### ISSUE THREAD

**Issue by Evecreate** [adobe/aem-core-wcm-components#396]
## Bug Report

**Current Behavior**
We are creating a list based on tagging, however as /etc/tags is closed on publish, we need add on the  publish server **jcr:read** rights on the **everyone** group in order for the list to be shown.

**Expected behavior/code**
I would expect for a system user with jcr:read rights /etc/tags rights to get the pages instead of the user accessing the website.

**Environment**
- AEM 6.3 SP3
- Core Components 2.2.0

**Comment by bpauli** [comment]
@Evecreate For using a tag based List component in AEM 6.3 it is required to alter the ACLs for `/etc/tags`. OOTB the anonymous user (everyone) is not able to read descendants tags from the tags root node because of the empty `rep:glob` restriction on `/etc/tags`. For more information on the `rep:glob` restriction please have a look to the docs at [1].

With the same mechanism it is possible to grant access very granulate for anonymous access. For instance if you only want to give permission to the tags located at /etc/tags/we-retail you can use the value `rep:glob=/we-retail` as shown in the screenshot.

![image](https://user-images.githubusercontent.com/689884/68692930-a1f9bd80-0576-11ea-8c90-9dc4627445be.png)


[1] https://jackrabbit.apache.org/oak/docs/security/authorization/restriction.html
