### ISSUE TITLE
Teaser : Add support for special characters eg. superscript or subscript in Title and description

### ISSUE THREAD

**Issue by rajeevyadav2** [adobe/aem-core-wcm-components#420]
## Feature Request

**Is your feature request related to a problem? Please describe.**
There are many scenarios where title and description needs special characters in teaser component. Current Teaser component doesnot support this feature and only option is to overlay and change the dialog.

**Describe the solution you'd like**
An option should be provided to choose between text field and rich text for title and description fields. Also option should be there to enable features in text if these are configured as rich text.(similar to text component)

**Are there alternatives?**
No alternatives.
**Documentation**

**Comment by andreeadracea** [comment]
@rajeevyadav2, thank you for your feature request! 
Could you please tell me which special characters are you trying to use? I am asking this because I checked and some of the most used special characters are accepted in title and description.

**Comment by gabrielwalt** [comment]
Hi Rajeev,

What you might mean with "special characters" is what we call "character styles", as you mention superscript and subscript. Other character styles could for example be bold, italics, etc.

While this would generally make sense, it would require a bigger refactoring of our Rich Text Editor (RTE), to support a mode in which it only allows authors to set character styles, but not paragraph styles (like bulleted/numbered lists, blockquote, etc). We'd need such a limitation, because it would otherwise generate invalid HTML when authors create paragraph styles for fields like a title text, as block-level like bulleted or numbered lists elements are not allowed inside `<h1>`-`<h6>` elements. Also, just limiting the features of the RTE when used for the title field wouldn't be sufficient as the RTE by default wraps every text in a paragraph element (inside a `<p>`), which would also lead to invalid markup when it's further placed inside a `<h1>`-`<h6>` element. So we'd truly need a special "inline" mode for the RTE to make what you describe possible.

Unfortunately, this is currently out of scope for the core components, and not a priority for the next few months. I'll however forward your request to the team who's maintaining the RTE as I agree that it would make sense to offer character styles for some fields, like the title text. Maybe they can find some bandwidth to improve that. However, I'm closing this issue here for now.

**Comment by rajeevyadav2** [comment]
@gabrielwalt : Right now, I want to have superscript and subscripts in title and description. Also there needs to be special characters/styles like registered copyright symbol etc. Most of the types these are the minimum things that we need when authoring the teaser.

**Comment by Vydeshramkumar** [comment]
Hi There - I am running into the same issue. If this feature is not yet available, is there any alternative solution for this use case?
