### ISSUE TITLE
[Teaser] Compatibility breaks after upgrading from 2.1.0 to 2.3.0

### ISSUE THREAD

**Issue by stevengssns** [adobe/aem-core-wcm-components#490]
There are HTML changes in the v1 release of the Teaser component. This should have been a version v2 because it can clearly break existing components (as it did in our case).

I takes a lot of effort to try and convince (mostly AEM averse front-end) developers to not develop their own new components and to try and use/extend existing core components.
Not to mention the fact that the core components are not very well extendible (one quickly ends up rewriting everything because of the lack of extension points).

Following commit add a.o. a wrapping DIV that is breaking our CSS.

https://github.com/adobe/aem-core-wcm-components/commit/10625bd0e0970ba3c76c0cbdb16e59123a45c85

**Comment by vladbailescu** [comment]
Hi Steven,

Thanks for bringing this up. We're sorry we broke stuff for you. We do have some versioning policies (https://github.com/adobe/aem-core-wcm-components/wiki/Versioning-Policies#html-markup), including one that states:

> Backwards compatible changes:
>
> * adding new markup/nodes that would not require a change of CSS selectors, or does not modify the markup's semantics

With the BEM-style selectors we figured adding a wrapper div for the actions would not impact people's stylesheets as they would normally use `cmp-carousel__content` and `cmp-carousel__action` or one of the action modifiers to address those elements.

Can you share your use case so we can learn from it and try to come up with better policies?

Also, since you mention lack of extension points, can you please elaborate on this (best in a different issue) and let us know which would be some convenient extension points for you/your team so we can have a constructive discussion and find out what we can improve?

Many thanks!

**Comment by vladbailescu** [comment]
@stevengssns, we need your feedback here, please let us know your use case to better understand how we can improve our policies and actions!

**Comment by stevengssns** [comment]
Hi @vladbailescu, I've been sick the past week, but I'm going to ask our front-end developers what exactly happened when I'm back at work tomorrow.

I'll also try to create a separate issue to try and list some pain points when it comes to extensibility.

**Comment by richardhand** [comment]
@stevengssns - were you able to gather more feedback from your frontend-devs here?

**Comment by stevengssns** [comment]
Sorry, for the later response. Recovering from a viral infection took a bit longer than expected...

The front-end developer provided me with the following explanation:

"Our css grid definition was defined on the wrapping element, so the added nested element breaks it. The elements once considered part of the grid are now no longer children of it, so the styling ceases to apply."

**Comment by richardhand** [comment]
No problem, thanks very much for the feedback. That was my suspicion, it would also be the case for a `flexbox` layout. I'll discuss this with the team and reflect the results in our [versioning policies](https://github.com/adobe/aem-core-wcm-components/wiki/versioning-policies). I think it's correct to say that _any_ markup additions in the template are potentially breaking to a page layout.

**Comment by gabrielwalt** [comment]
+1 we want to harden the version policy to prevent adding elements to the output markup without creating a new version.

**Comment by richardhand** [comment]
This is now reflected in the markup versioning policy https://github.com/adobe/aem-core-wcm-components/wiki/Versioning-Policies#html-markup, closing this issue.
