### ISSUE TITLE
[ContentFragmentList] Add UI Tests

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#522]
The newly-created Content Fragment List component is missing UI (Hobbes) test coverage. This should be added.

CQ-4266568

**Comment by jckautzmann** [comment]
Fixed with PR:
https://github.com/adobe/aem-core-wcm-components/pull/547

As part of the PR, following updates have been made:
- create UI tests: set the parent path, set the tag names, set element names
- introduce content fragments: carousel-fragment, image-fragment, text-fragment, simple-fragment:
/content/dam/core-components/contentfragments-tests
- introduce a content fragment model:
/conf/core-components/settings/dam/cfm/models/core-component-model
- introduce tags: basic and container:
/content/cq:tags/core-components

**Comment by richardhand** [comment]
This is available on the master branch and will be included in the upcoming [2.4.0](https://github.com/adobe/aem-core-wcm-components/milestone/11) release.
