### ISSUE TITLE
[ContentFragment] Add UI tests

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#524]
The newly-moved Content Fragment component outside of the extension folder is missing UI (Hobbes) test coverage. This should be added.

CQ-4266569

**Comment by jckautzmann** [comment]
Fixed with PR:
https://github.com/adobe/aem-core-wcm-components/pull/550
As part of the PR, following updates have been made:
- create UI tests: set the fragment path, set the variation name, test a structured CF, set element names
- replace: cmp-contentfragment__edit-dialog -> cmp-contentfragment__editor
- add the missing BEM classes to the README
- add a link to the content fragment list in the main README

**Comment by richardhand** [comment]
This is available on the master branch and will be included in the upcoming [2.4.0](https://github.com/adobe/aem-core-wcm-components/milestone/11) release.
