### ISSUE TITLE
[Form Container (v2)] Policy Responsive Settings Columns property does not apply

### ISSUE THREAD

**Issue by slocum-adobe** [adobe/aem-core-wcm-components#745]
## Bug Report

**Current Behavior**
As an author, I navigate to the core component template and configures the policy of the Form Container (v2). I navigate to the Responsive Settings tab, and configure the number of columns to 2. I save the change. I then drag and drop the Form Container (v2) onto the core component page. The responsive columns are not applied to my form container. There is a single parsys. 

**Expected behavior/code**
As an author, I expect there to be two columns within my form container to add form components to. 

**Environment**
- AEM 6.5 SP 1
- Core Components version 2.5.0
- JRE version jdk1.8.0_181.jdk

**Comment by JasonUSC** [comment]
This bug is a blocker in our implementation so hopefully it gets fixed asap.

**Comment by bpauli** [comment]
@JasonUSC @slocum-adobe Actually this is not a bug :). The Form Container reuses the same functionality as the layout container. The responsive settings in the content policy does only control how many columns an author can use when you resize the components in the layout mode. For more information please have a look to the corresponding documentation for the layout container at [1]. Please make sure that you import the Responsive CSS to you own client lib as described on the same helpx page, otherwise the Layout Mode will not work.

[1] https://helpx.adobe.com/experience-manager/6-5/sites/administering/using/configuring-responsive-layout.html#ConfiguretheGridoftheLayoutContainer

**Comment by gabrielwalt** [comment]
This seems to work as designed: configuring a form container to 2 columns doesn't mean that 2 columns will be created when inserting a form container to the page, but it means that any container inside of it can be resized to only 2 columns (instead of 12 by default).
