### ISSUE TITLE
[Image] Drag & drop SVG on image component not working

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-core-wcm-components#825]
Setting an SVG image works through the dialog, but not through direct drag & drop from the content finder onto the image component.

Something seems to be wrong on the component `cq:editConfig` configuration drop target configuration of the core component and of all proxy components (Archetype, WKND):
`/apps/core/wcm/components/image/v2/image/cq:editConfig/cq:dropTargets/image`

On the `cq:editConfig/cq:dropTargets/image` node, adding the `accept` MIME type `“image/svg”` makes it work. There might be a bug with the existing `“image/svg+xml”` MIME type.

**Comment by richardhand** [comment]
The `accepts` config expects a regular expression, which is why `image/svg+xml` matches `image/svg` correctly. Solution is to escape the +:

AEM Core Components:
https://github.com/adobe/aem-core-wcm-components/pull/826

AEM Project Archetype:
https://github.com/adobe/aem-project-archetype/pull/268

WKND Guide:
https://github.com/adobe/aem-guides-wknd/pull/48

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
