### ISSUE TITLE
[Page] Link tags configuration in page properties to improve loading time

### ISSUE THREAD

**Issue by surya057** [adobe/aem-core-wcm-components#848]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Establishing the connection to third part JS involves significant time in networks, particularly when it comes to secure connections, as it may involve DNS lookups, redirects, and several round trips to the final server that handles the user’s request. 
Taking care of all this ahead of time can make your application feel much snappier to the user without negatively affecting the use of bandwidth. Most of the time in establishing a connection is spent waiting, rather than exchanging data.

**Describe the solution you'd like**
Adding a preconnect tag to head.html will open the connection parallelly while DOM loads and makes the asset/JS download faster.

configuration for this should be in page properties so whenever asset/JS file change content editor can go to the particular page's property and change it.

Example: https://github.com/surya057/AEM-site-optimization/tree/master/aem-site-optimization 

**Are there alternatives?**
open for suggestions, but I don't have any alternative solution for it.

**Documentation**
Implementation - https://github.com/surya057/AEM-site-optimization/tree/master/aem-site-optimization
Preconntect doc - https://www.keycdn.com/blog/resource-hints

**Comment by gabrielwalt** [comment]
Hi @surya057, this sounds interesting. I'm curious about how other projects need these optimization `<link>` tags to work.

My feedback would be the following. It seems to me that:
* it would rather be a super-author or developer role to maintain these link tags;
* such properties should rather be defined only once for an entire site, or at least for an entire template.

Option A: If it is a developer task to define the value for these link tags, and if these properties should are site-wide, then it is then fairly easy for the developer to customize the site-specific `head.html` file in the page component proxy. But then, there's not much to do… Maybe we could just have these link tags in the `head.html` template, but commented out, so that a developer can easily fill them as needed.

Option B: If we want to make this more of configurable super-author task, or if we want to give some more per-template control for these `link` tags, then these could then be options for the design dialog.

If you'd like this feature to be added to the Core Components, I suggest that you create a pull request. And in the PR, if going with option B, I'd also expect that fetching the properties would go through the `com.adobe.cq.wcm.core.components.models.Page` SlingModel. And one small detail while I'm at it: avoid to use the HTL `<sly>` element or `data-sly-unwrap` attribute when it's not necessary; typically in your `head.html` script [1], you could simplify the iteration as follows:
`<link data-sly-repeat="${properties['cq:preconnect']}" rel="preconnect" href="${item}" crossorigin />`

[1] https://github.com/surya057/AEM-site-optimization/blob/master/aem-site-optimization/ui.apps/src/main/content/jcr_root/apps/siteopt/components/structure/page/head.html#L26

**Comment by surya057** [comment]
Hi @gabrielwalt, Thank you for the input, I will take the option B.
