### ISSUE TITLE
[Library] UX changes for Core Components library

### ISSUE THREAD

**Issue by gknobloch** [adobe/aem-core-wcm-components#876]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Make changes to Core Components library
* Colored icons
* Introduce categories of components
* 4 components per row (instead of 3)

**Describe the solution you'd like**
@gabrielwalt should define the exact categories/order

**Documentation**
PoC which doesn't have the latest icons yet, and still 3 columns.
<img width="606" alt="Poc" src="https://user-images.githubusercontent.com/1628642/70523431-58839a80-1b43-11ea-8790-9608c8c5cc3d.png">
(ignore Commerce components, that was just to show categories)

**Comment by gknobloch** [comment]
[SVG_180.zip](https://github.com/adobe/aem-core-wcm-components/files/3944445/SVG_180.zip)

**Comment by gknobloch** [comment]
When working on the PoC, I’ve seen some limitations in the way we could group efficiently (more longer term improvements).

For the left navigation list:
• I had to add multiple navigation components, create the category page, and move the components under the right categories (right now, each component gets its own page at the root)
• Above each navigation entry, I added a title component
I could imagine a navigation could be built out of tags

When it comes to the main content, it’s one teaser component per component
* I could imagine we’d have a “Teaser List” or basically a Generic List component, where you define which component to use to render list items - it would obviously have limitations when it comes to the properties you can manage, but you could then manage at each list item level

**Comment by richardhand** [comment]
> 4 components per row (instead of 3)
This will probably require a redesign of the cards to reduce their width e.g. by removing or wrapping the descriptions - 4 components don't fit for the case where the left sidebar is showing and screen width is narrow.

> Introduce categories of components
• We already have some category tags (below) applied to each component so we should be able to reuse those, and adapt them based on the new classifications by @gabrielwalt:

<img width="520" alt="Screenshot 2019-12-10 at 12 40 56" src="https://user-images.githubusercontent.com/25616660/70526697-76a0c900-1b4a-11ea-9a88-b5d2489205b6.png">

• For the home page view, I'd like to propose an alternative, to make the category selection part of the filtering rather than as set headings, which is repetitive of what's already in the sidebar. Something like the following below the search bar:

<img width="351" alt="Screenshot 2019-12-10 at 12 22 02" src="https://user-images.githubusercontent.com/25616660/70525829-7d2e4100-1b48-11ea-8e75-280ec2c3348a.png">

Or with another UI element such as tags.

**Comment by richardhand** [comment]
https://github.com/adobe/aem-core-wcm-components/pull/890
