### ISSUE TITLE
[Tab][Accordion][Carousel] Panel select action not displayed in the editable template editor

### ISSUE THREAD

**Issue by rajeevyadav2** [adobe/aem-core-wcm-components#901]
I am trying to author Tabs/Carousel/Accordion in Editable Template. These components are not giving toggling option on editbar when multiple items are added in these components. If I author on pages, it works fine.

**Comment by richardhand** [comment]
Thanks @rajeevyadav2 for the bug report, I was able to replicate the behaviour on AEM latest with Core Components 2.8.0. The problem seems related to the condition at [0] that adds the panel select action to the toolbar. It should probably be made more general, or to also include template editing modes.

[0] - https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/panelselect/js/panelselect.js#L420

**Comment by rajeevyadav2** [comment]
@richardhand : Thank you for confirmation. Could you please confirm when can we expect the fix for this bug.

**Comment by richardhand** [comment]
@rajeevyadav2 - We don't have a set date yet for the next release of the Core Components, but the best way to ensure this fix gets in is to create a pull request. 

Regarding the solution, it should be enough to expand the logic at [0] to check the current layer against the template editor "structure" and "initial" modes.

[0] - https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/panelselect/js/panelselect.js#L421

**Comment by rajramo61** [comment]
@rajeevyadav2 / @richardhand I can pick this item up if you are okay.

**Comment by richardhand** [comment]
@rajeevyadav2 - that would be great! Thanks

**Comment by rajeevyadav2** [comment]
@rajramo61 Please go ahead.
