### ISSUE TITLE
Text Component: Show all plugins by default

### ISSUE THREAD

**Issue by manojBabuDev** [adobe/aem-core-wcm-components#937]
Currently, we use classic page templates, not editable templates yet. For all plugins to show up in the **text component**; every time our content authors has to go to design dialog and enable all plugins. It's better if we have an override configuration/authoring field so that by default all plugins show up text component for authors.

**Comment by gabrielwalt** [comment]
Hi @manojBabuDev, as documented [0], static templates are not supported by the Core Components, please check out the AEM Modernization Tools [1] to migrate to editable components, so that this issue doesn't happen to you anymore.

[0] https://github.com/adobe/aem-core-wcm-components#system-requirements
[1] https://opensource.adobe.com/aem-modernize-tools/pages/tools.html
