### ISSUE TITLE
Change component ID format to use underscores

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-core-wcm-components#993]
Change the format of the component IDs to use underscores (`_`), instead of dashes (`-`).
Eg: `"carousel_1234567890"`, instead of `"carousel-1234567890"`

The reason is that when we’re using these IDs also in the Data Layer JSON as key for each component, using underscores would avoid having to escaping them when accessing the state. Eg:
```js
// Basic:
var state = adobeDataLayer.getState();
var accordion = state.component.accordion_1234567890;

// Or if getState() supports JSON paths:
var accordion = adobeDataLayer.getState("component.accordion_1234567890");

// And when using events:
adobeDataLayer.addEventListener("cmp:show", fuction(event) {
    console.log(event.info.component); // eg: "component.accordion_1234567890_item_1234567890"
    var accordionItem = adobeDataLayer.getState(event.info.component);
    var accordion = adobeDataLayer.getState(accordionItem.parent);
});
```

**Comment by vladbailescu** [comment]
The general recommendation is to use hyphens to separate words in class names and IDs:

https://developer.mozilla.org/en-US/docs/Archive/Beginner_tutorials/Underscores_in_class_and_ID_Names

See also https://google.github.io/styleguide/htmlcssguide.html#ID_and_Class_Name_Delimiters

AFAIR, this is because browsers usually expose global objects for node IDs and having a hyphen will not allow you to confuse a local variable with that global object:

```
<div id="id_1">...</div>
```
can be used in global scope
```
alert(id_1);
```
while
```
<div id="id-2">...</div>
```
cannot.

**Comment by gabrielwalt** [comment]
Thanks, Vlad, closing this then.

While the same is theoretically also possible to run into variable collisions with `id-2` as that also creates a global variable, I get the point that in practice it's much less likely to run into a variable naming collision with dashes given that the more painful notation has to be used:
```
alert(window["id-2"]);
```

Basically, we don't want to go against general practices and recommendations.
